### ISSUE TITLE
Discord Login service

### ISSUE THREAD

**Issue by Almantask** [csinn/CSInn#1]

**Comment by westonpace** [comment]
I think this issue needs more of a description.  I had originally thought you wanted to support logging into the C# inn website using Discord credentials.  For an example, look at https://discord.io/

However, if that is your goal, then you wouldn't need stories for a login page or a registration page (registration may still be used later to query additional details from a user the first time they login).

So there are two approaches, login with discord credentials and login with csinn credentials.  Which approach are you looking to support in the first sprint?  Or are you looking to support both approaches this first sprint?

**Comment by Almantask** [comment]
I think we should be minimalistic first. Logging in with discord credentials could be enough for now. If user does not have a valid login, we will redirect to invite link for discord account create page.

**Comment by Almantask** [comment]
Later on we will have meaningful roles like mentor and admin. Then we can add custom handling on top.

**Comment by Almantask** [comment]
Ideally, I had in mind that we can create and join discord account and our website account, upon completing registration on website.

Not sure how realistic is thst though.

**Comment by spnm** [comment]
So are we going to use Discord.NET to build our authorization?

**Comment by Almantask** [comment]
What options do we have?

**Comment by trinitrotoluene** [comment]
I would suggest taking a look at the middleware implemented [here](https://github.com/RogueException/Discord.OAuth2). The NuGet package may not be up to date, but we can certainly fork/adapt it to our own needs or just add it as a submodule if it works as we'd like it to.

**Comment by westonpace** [comment]
That middleware looks good.  It isn't much code anyways.  It builds on top of ASP.NET core's existing OAuth support to tell it where to get the user token.

At this point I don't think we need Discord.NET.  I think the amount of glue needed to connect Discord.NET to ASP.NET would be equal to or greater than the amount of glue in this extension.

**Comment by trinitrotoluene** [comment]
Closing this in favour of continuing discussion in #25.
