### ISSUE TITLE
Pick database 

### ISSUE THREAD

**Issue by Almantask** [csinn/CSInn#17]
We need to decide which database to use.

**Comment by norarrsgd** [comment]
SQL Server (T-SQL) would be nice. Pair it up with EF Core. Or if you guys want, we can use dapper to have the performance close to ADO

**Comment by Almantask** [comment]
About specific database I am not sure, but ORM-wise, EF Core is better suited for our needs. We're not a company with millions of records, top performance is not an issue as of today.

**Comment by norarrsgd** [comment]
> About specific database I am not sure, but ORM-wise, EF Core is better suited for our needs. We're not a company with millions of records, top performance is not an issue as of today.

True. SQL Server then 👍

**Comment by trinitrotoluene** [comment]
I'd suggest PostgreSQL as an alternative. There's an excellent EfCore driver for it, and it's faster under concurrent load.

**Comment by norarrsgd** [comment]
Should we have a vote for what to use?

**Comment by EmKa-dev** [comment]
I'm fine with anything, I'm fine with PostgreSQL.

**Comment by Almantask** [comment]
I have always worked with either SQLite, MySQl, T-SQL. I personally find PostgreSQL as a nice new touch. Reading DB choice reviews, I see many people in love with PostgreSQL. Seems that it is a proper implementation for a database, have least quirks compared to the rest. Lastly, it's open source, so it complements our tooling choices :)

**Comment by Almantask** [comment]
Choice: PostgreSQL.
