### ISSUE TITLE
Branch Strategy

### ISSUE THREAD

**Issue by norarrsgd** [csinn/CSInn#24]
GitFlow anyone?

**Comment by ooojustin** [comment]
gitflow sounds good to me.

```
master
dev
    - feature/
    - release/
    - hotfix/
```

**Comment by HelloWorld183L** [comment]
Agreed

**Comment by norarrsgd** [comment]
I see someone has already implemented it. Closing this issue now. For anyone not familiar with GitFlow, read [this](https://datasift.github.io/gitflow/IntroducingGitFlow.html).
