### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by trinitrotoluene** [csinn/CSInn#26]
The project is currently unlicensed. We should probably change that in favour of a popular OS license.

MIT seems like a good fit, unless someone wants to make a case for a different one?

**Comment by ooojustin** [comment]
Agreed.
MIT should be perfect for this project.
https://github.com/csinn/CSInn/pull/27

**Comment by jasonkuo41** [comment]
+1 MIT would be more than enough

**Comment by Almantask** [comment]
MIT license added.
