### ISSUE TITLE
properly do button spacing, get rid of divs

### ISSUE THREAD

**Issue by Alumniminium** [csinn/CSInn#45]
Assigned Salty as he said it's already on his To-do list :)

https://github.com/csinn/CSInn/blob/0139302c40c7d34413677c05dce135b6ae02017b/src/CSInn.Presentation.Blazor/Pages/_Mainpage.cshtml#L15-L21

**Comment by andrijajocic** [comment]
I'll try and fix it later today if I have time.

**Comment by andrijajocic** [comment]
After looking into multiple StackOverflow threads and random internet articles, I've noticed that there isn't any other efficient way to space out multiple buttons. Unless @Alumniminium or someone else knows a more efficient way to do this, I'll be closing the issue for now.

**Comment by andrijajocic** [comment]
can someone please remind me what this was about? i was absent from the project for some time and lost track :(

**Comment by Developeneur** [comment]
@andrijajocic Are you still working on this?
